# Enable fully-featured C++
CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_STD_CPP20=y # C++20 ISO standard
CONFIG_CPP_EXCEPTIONS=n
CONFIG_CPP_RTTI=n
# Enable GNU-style static constructors
CONFIG_STATIC_INIT_GNU=y

# Enable all SPN modules
CONFIG_SPN_CORE=y
CONFIG_SPN_EXAMPLE_LIB=y
CONFIG_SPN_LOGGING=y
CONFIG_SPN_DEBUGGING=y
CONFIG_SPN_THREADING=y
CONFIG_SPN_TIMING=y
CONFIG_SPN_SYSTEM=y
CONFIG_SPN_ALLOCATION=y
CONFIG_SPN_CONTAINERS=y
CONFIG_SPN_DEPENDENCY_INJECTION=y

# Enable logging
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_MAIN_STACK_SIZE=2048