# Enable fully-featured C++
CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_STD_CPP20=y # C++20 ISO standard
CONFIG_CPP_EXCEPTIONS=n
CONFIG_CPP_RTTI=n
# Enable GNU-style static constructors
CONFIG_STATIC_INIT_GNU=y

CONFIG_SPN_DEBUGGING=y
CONFIG_SPN_ASSERT_LEVEL=2
CONFIG_SPN_ASSERT_HANDLER=y

# enable the assertion handler, so that unhandled asserts will crash through the Zephyr assertion system
CONFIG_ASSERT=y